name: Testing imaging - docker-image-versioning

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop-image-versioning'
    tags:
      - 't*'
  pull_request:
    branches:
      - 'develop-image-versioning'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: output info
      run: |
        - echo "env.IMAGE_NAME = ${{env.IMAGE_NAME}}"
        - echo "env.REGISTRY = ${{env.REGISTRY}}"

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
#         images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          images: densom/github-self-hosted-runner
        
    # - name: Build and push
    #   uses: docker/build-push-action@v3
    #   with:
    #     context: .
    #     push: ${{ github.event_name != 'pull_request' }}
    #     tags: ${{ steps.meta.outputs.tags }}
    #     labels: ${{ steps.meta.outputs.labels }}
