name: Testing imaging - docker-image-versioning

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - 'docker-image-versioning'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set runner version
      id: runner-version
      uses: juliangruber/read-file-action@v1
      with:
        path: .github-runner-version

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
      
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
#         images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          images: densom/github-self-hosted-runner
        
    # - name: Build and push
    #   uses: docker/build-push-action@v3
    #   with:
    #     context: .
    #     push: ${{ github.event_name != 'pull_request' }}
    #     tags: ${{ steps.meta.outputs.tags }}
    #     labels: ${{ steps.meta.outputs.labels }}
    #     build-args: |
    #       - RUNNER_VERSION: ${{ steps.package.outputs.content }}
