name: Docker Image CI

on:
  workflow_dispatch:
    
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:

  build:

    # runs-on: ubuntu-latest
#     runs-on: dennis-test-runner
    runs-on: [self-hosted]

    steps:
    - run: echo work in progress
#     - uses: actions/checkout@v3
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
